name: PDF Processing Pipeline

on:
  push:
    paths:
      - 'DATA/raw_pdfs/**'
  pull_request:
    paths:
      - 'DATA/raw_pdfs/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  process-pdfs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for better change detection
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create DATA directories
      run: |
        mkdir -p DATA/raw_pdfs
        mkdir -p DATA/embeddings
        
    - name: Check for PDF changes
      id: check_changes
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "Manual trigger - processing all PDFs"
          echo "process_all=true" >> $GITHUB_OUTPUT
        else
          # Get list of changed files
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # For pull requests, compare with the base branch
            git fetch origin ${{ github.base_ref }}
            git diff --name-only origin/${{ github.base_ref }} HEAD > changed_files.txt
          else
            # For pushes, compare with the previous commit
            git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > changed_files.txt
          fi
          
          if grep -q "DATA/raw_pdfs/.*\.pdf$" changed_files.txt; then
            echo "PDF changes detected - processing changed PDFs"
            echo "process_all=true" >> $GITHUB_OUTPUT
          else
            echo "No PDF changes detected - skipping processing"
            echo "process_all=false" >> $GITHUB_OUTPUT
          fi
        fi
        
    - name: Process PDFs
      if: steps.check_changes.outputs.process_all == 'true'
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Starting PDF processing..."
        # Run the PDF processor script directly
        python pdf_processor.py
        
    - name: Commit processed files
      if: steps.check_changes.outputs.process_all == 'true' && github.event_name != 'pull_request'
      run: |
        git config --local user.email "kunaldmohare@gmail.com"
        git config --local user.name "Mohare786-Kunal"
        git add DATA/embeddings/ DATA/pdf_metadata.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update PDF embeddings [skip ci]"
        fi
        
    - name: Push changes
      if: steps.check_changes.outputs.process_all == 'true' && github.event_name != 'pull_request'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: ${{ github.ref }}
        force: false 